### ISSUE TITLE
VB.net WinForms example

### ISSUE THREAD

**Issue by birbilis** [panthernet/GraphX#19]
I tried to do a rebuild all at the latest GraphX that GitHub Desktop brought to my machine

at the C# WindowsFormsProject I had to right click and Manage NuGet Packages, then had to select to restore missing NuGet Packages. Not sure if this is by design to avoid checking in QuickGraph's code

(1) at the WindowsDesktop_VB.NET_WinForms_Example (that one btw could have a better project name, could strip the WindowsDesktop_ prefix and maybe rename to Example.WinForms.VB) I had to manually add an extra NuGet Package for "YAXLib" to build

(2) now I have a warning at Models\DataEdge.vb in that project at "ToString" where it says you're shadowing the ToString method of the ancestor instead of overriding it. That is an "Overrides" qualifier is missing there. That will cause issue if the ToString method is called from code that accepts an Object or any other ancestor of DataEdge, since it will call the original ToString, not this method. I also see "0 references" in hint above the function, so I guess "Overrides" is indeed missing there, since it isn't called explicitly

**Comment by panthernet** [comment]
Ops! Found missed import request for YAXLib in VB project. Will fix it, thanks! Will fix ToString() method too. I'm not familiar with VB and haven't looked deep at this project since i've wrote it first time :)

I think you have to restore NuGet packages manualy if your NuGet isn't configured to do this automaticaly on project  build.

**Comment by birbilis** [comment]
if these have been done, can close the issue
